name: run pollbot.py

on:
  workflow_dispatch:
    secrets:
      TOKEN:
        required: true
        description: ''
       CHAT_ID:
        required: true
        description: ''
  
jobs:
  send_poll:
    runs-on: ubuntu-latest
    steps:
    - name: send poll
      secrets:
        TOKEN: {{$TELEGRAM_BOT_TOKEN}}
        CHAT_ID: {{$TELEGRAM_CHAT_ID}}
      run: python pollbot.py
