name: run pollbot.py

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: execute py script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python pollbot.py
