name: run pollbot.py

on:
  schedule:
    - cron '0 15 * * 5' # every Friday on 15h
on: [push]

jobs:
  send_poll:
    runs-on: ubuntu-latest
    steps:
    - name: send poll
      env:
        TOKEN: {{$TELEGRAM_BOT_TOKEN}}
        CHAT_ID: {{$TELEGRAM_CHAT_ID}}
      run: python pollbot.py
