name: run pollbot.py

on:
  workflow_dispatch

jobs:
  send_poll:
    runs-on: ubuntu-latest
    steps:
    
    - name: send poll
      env:
        TOKEN: {{ $secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: {{ $secrets.TELEGRAM_CHAT_ID }}
      run: python pollbot.py
